title: อิสราศรม
description: เพื่อความเข้าใจพุทธศาสนาอย่างมีเหตุผล 
theme: just-the-docs

url: https://bhaddacak.github.io/israsomtest
jsassets_url: "https://bhaddacak.github.io/assets/js"
ncped_url: "https://bhaddacak.github.io/assets/ncped"
#jsassets_url: "http://localhost:4000/assets/external/js"
#ncped_url: "http://localhost:4000/assets/external/ncped"

color_scheme: light
theme_switch: true
search_enabled: true
search:
  tokenizer_separator: /[\s\-\(\)/]+/
back_to_top: true
back_to_top_text: "กลับด้านบน"

aux_links:
  "bhaddacak.github.io":
    - "https://bhaddacak.github.io"
aux_links_new_tab: true

footer_content: "Copyright &copy; 2023-2026 <a href=\"https://bhaddacak.github.io\">J.R. Bhaddacak</a>, licensed under <a href=\"https://creativecommons.org/licenses/by-nc-nd/4.0/\">CC BY-NC-ND 4.0</a>"

last_edit_timestamp: true
last_edit_time_format: "%e %B %Y"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  remark:
    color: blue
  remember:
    title: ข้อควรจำ
    color: green
  question:
    title: คำถาม
    color: purple
  warning:
    title: ระวัง
    color: red


plugins:
  - jekyll-seo-tag
