title: อิสราศรม
description: เพื่อความเข้าใจพุทธศาสนาอย่างมีเหตุผล 
theme: just-the-docs

url: https://bhaddacak.github.io/israsomtest

aux_links:
  "bhaddacak.github.io":
    - "https://bhaddacak.github.io"
